### ISSUE TITLE
Logs are not available

### ISSUE THREAD

**Issue by semenoh** [wultra/ssl-pinning-android#24]
`WultraDebug` is inner class so it is not possible to set any other value for debug purpose. Could you please use standart [isLoggable()](https://developer.android.com/reference/android/util/Log#isLoggable(java.lang.String,%20int)) method. This way it should be possible to set log level with adb command.

**Comment by hvge** [comment]
We can, at least, make that `WultraDebug` class public and visible for app developers. I'm leaving this decision on Tomas.
