### ISSUE TITLE
Support for React native version

### ISSUE THREAD

**Issue by moxspoy** [wultra/ssl-pinning-android#49]
Hallo everyone!

Is there are react native version for this library? or some workaround to implement?

I have looked at https://github.com/MaxToyberman/react-native-ssl-pinning, but it seems like they dont support dynamic SSL Pinning.

Thank you.

**Comment by hvge** [comment]
Hello,
thank you for your question, but unfortunately, we don't have react native version of this library.  We can provide a wrapper later, but it depends on our customers demand.
Thanks.

**Comment by petrdvorak** [comment]
Hello @moxspoy, just to encourage you for open-source software contributions a bit, you can implement a wrapper around our APIs in React Native yourself by following these docs: https://reactnative.dev/docs/native-modules-intro This would indeed help the React Native community.

However, we are not able to support you in this very much. As @hvge said, we do not have the resources to maintain a React Native wrapper unless we have a customer on that.
