### ISSUE TITLE
The application crashes

### ISSUE THREAD

**Issue by mahramane** [wultra/ssl-pinning-android#50]
error :
Caused by: java.lang.ClassNotFoundException: Didn't find class "io.getlime.security.powerauth.keychain.KeychainFactory" on path

**Comment by hvge** [comment]
Duplicate #38

**Comment by hvge** [comment]
Be aware that library version 1.1.x+ requires at least PowerAuth mobile SDK 1.4.2 and newer. This requirement is due to improvements in the secure data storage we have implemented in that version of the SDK.
