### ISSUE TITLE
Certificate verifier returns "EMPTY" in android device with OS 7 (Marshmallow)

### ISSUE THREAD

**Issue by divyeshdhedhi** [wultra/ssl-pinning-android#63]
Tried different approaches to resolve this issue but no luck. Please can anyone comment on this issue of certificate is not getting verified in android 7 devices

**Comment by petrdvorak** [comment]
Hello @divyeshdhedhi, we do not know what you do in you code, what task you are trying to achieve, nor what the actual incorrect result is for you. Please provide a more detailed issue description (have a look at [these guidelines](https://developers.wultra.com/products/mobile-security-suite/2021-05/powerauth-crypto/Reporting-Issues)), or use discussions if you only need to ask assorted questions.

Also, the code is fully open-source. You can debug the code yourself and see why the results are what they are, and why they only happen on a specific device.
