### ISSUE TITLE
periodicUpdateIntervalMillis unexpected behavior

### ISSUE THREAD

**Issue by fmestre01** [wultra/ssl-pinning-android#64]
Hello, how are you? we are integrating the wultra component in one of our apps but we are having doubts about updating certificates. The "periodicUpdateIntervalMillis" parameter is apparently not working. How can we guarantee that whenever the certificate is renewed on the server (.json) the component will read it please.

**Comment by fmestre01** [comment]
thanks for the quick response. we will review suggestions and comments.

**Comment by petrdvorak** [comment]
There was no followup to this issue, I assume that the issue was either resolved or abandoned.
