### ISSUE TITLE
Infinite stacking of cached same certificates with updates

### ISSUE THREAD

**Issue by vstudnicka-cen66454** [wultra/ssl-pinning-android#65]
CertStore.kt -> private fun processReceivedData(...) -> updateCachedData { cachedData -> ... }

This does check not work:
if (newCertificates.indexOf(newCertificateInfo) != -1) {
    // skip entry that's already in the database
    continue
}

Everytime it downloads trustlist it is checking if certificate is already in array. For every CertificateInfo it is creating new object and this code above is checking if same object is already in cachced array, but not comparing its data but only if it is same object. This results in in adding same certificate everytime it updates as it is always a newly created CerticateInfo object

![image](https://user-images.githubusercontent.com/84183998/172171147-b7c63b9c-560a-46b7-bc2d-b2ef4c0bf5e4.png)

**Comment by petrdvorak** [comment]
@TomasKypta Thank you for reporting, adding @TomasKypta.

**Comment by tanvir-retailai** [comment]
@petrdvorak any update on this ticket?
