### ISSUE TITLE
Optimize consumer proguard rules to handle R8

### ISSUE THREAD

**Issue by TomasKypta** [wultra/ssl-pinning-android#74]

**Comment by tanvir-retailai** [comment]
@TomasKypta @petrdvorak 
I am planning to use your library into a PROD environment therefore, do you guys have any plan to implement this ticket any time soon? much appreciate ....

**Comment by petrdvorak** [comment]
Hello @tanvir-retailai, thank you for the comments - we will review the issues asap and prepare a new version. We already use the library in production but need to port all the fixes to this opensource repo too.

Also, could you ping me at petr@wultra.com? I would love to learn a bit more about your app and see if we can help you with some other securoty issues, or maybe provide a hosted version of dynamic SSL pinning.

**Comment by tanvir-retailai** [comment]
@petrdvorak I sent you a mail
